/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelprojectgui;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author USER
 */
public class KamarHotelMilos extends javax.swing.JFrame {
 
    /**
     * Creates new form KamarHotelMilos
     */
    public KamarHotelMilos() {
        initComponents();
           Buttonku();
        this.setLocationRelativeTo(null);
        
    }

    private void Buttonku() {
        ButtonGroup bg1 = new ButtonGroup();
        
        bg1.add(ya);
        bg1.add(tidak);
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        nokamar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tipekamar = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        tidak = new javax.swing.JRadioButton();
        ya = new javax.swing.JRadioButton();
        btntambah = new javax.swing.JButton();
        btnubah = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        hapusdtall = new javax.swing.JButton();
        srcnama = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablekamar = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelpic/aweeu.png"))); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 280, 280));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Halo, Admin!");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("© Adri, Rama, Teguh");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 810, -1, 20));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelpic/LOGOUT.png"))); // NOI18N
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 550, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelpic/wqw.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 20, -1, 60));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel2.setText("MANAJEMEN KAMAR");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));
        jPanel1.add(nokamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, 220, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("No Kamar  :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Reserved :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, -1, -1));

        tipekamar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih Tipe Kamar-", "Standard", "Superior", "Deluxe", "Suite" }));
        jPanel1.add(tipekamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 220, 50));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Jenis Kamar :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, -1, -1));

        tidak.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tidak.setText("Tidak");
        tidak.setContentAreaFilled(false);
        jPanel1.add(tidak, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 380, -1, -1));

        ya.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ya.setText("Ya");
        ya.setContentAreaFilled(false);
        ya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yaActionPerformed(evt);
            }
        });
        jPanel1.add(ya, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, -1, -1));

        btntambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelpic/TAMBAH1.png"))); // NOI18N
        btntambah.setContentAreaFilled(false);
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });
        jPanel1.add(btntambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, 100, 60));

        btnubah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelpic/ubah1.png"))); // NOI18N
        btnubah.setContentAreaFilled(false);
        btnubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubahActionPerformed(evt);
            }
        });
        jPanel1.add(btnubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, 100, 60));

        btnhapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelpic/hapus1.png"))); // NOI18N
        btnhapus.setContentAreaFilled(false);
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 440, 100, 60));

        hapusdtall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelpic/hapusall.png"))); // NOI18N
        hapusdtall.setContentAreaFilled(false);
        hapusdtall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusdtallActionPerformed(evt);
            }
        });
        jPanel1.add(hapusdtall, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 520, 260, 60));

        srcnama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                srcnamaKeyReleased(evt);
            }
        });
        jPanel1.add(srcnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 150, 220, 40));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelpic/111searc.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 140, 60, 60));

        tablekamar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No Kamar", "Jenis Kamar", "Reserved"
            }
        ));
        jScrollPane1.setViewportView(tablekamar);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 220, 410, 580));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Selamat datang di sistem informasi Hotel Milos.");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, -1, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelpic/wadidwa.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 840));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        LoginFormHotel lfh = new LoginFormHotel();
        lfh.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MenuHotelMilos mhm = new MenuHotelMilos();
        mhm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void yaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yaActionPerformed

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tablekamar.getModel();
        model.addRow(new Object[]{nokamar.getText(),
            tipekamar.getSelectedItem().toString(), ya.isSelected(),
            tidak.isSelected()});
    }//GEN-LAST:event_btntambahActionPerformed

    private void btnubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnubahActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tablekamar.getModel();
        int row = tablekamar.getSelectedRow();
        if(row>=0){
            int ok=JOptionPane.showConfirmDialog(null, "Yakin Mau Hapus?","Konfirmasi",JOptionPane.YES_NO_OPTION);
            if(ok==0){
                model.removeRow(row);

            }
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void hapusdtallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusdtallActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tablekamar.getModel();
        int ok=JOptionPane.showConfirmDialog(null, "Yakin Mau Hapus?","Konfirmasi",JOptionPane.YES_NO_OPTION);
        while (model.getRowCount() > 0){

            for (int i = 0; i < model.getRowCount(); ++i){
                model.removeRow(i); } }
    }//GEN-LAST:event_hapusdtallActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void srcnamaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_srcnamaKeyReleased
       DefaultTableModel model=(DefaultTableModel)tablekamar.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        tablekamar.setRowSorter(tr);
            tr.setRowFilter(RowFilter.regexFilter(srcnama.getText().trim()));
        // TODO add your handling code here:
    }//GEN-LAST:event_srcnamaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KamarHotelMilos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KamarHotelMilos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KamarHotelMilos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KamarHotelMilos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KamarHotelMilos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btntambah;
    private javax.swing.JButton btnubah;
    private javax.swing.JButton hapusdtall;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nokamar;
    private javax.swing.JTextField srcnama;
    private javax.swing.JTable tablekamar;
    private javax.swing.JRadioButton tidak;
    private javax.swing.JComboBox<String> tipekamar;
    private javax.swing.JRadioButton ya;
    // End of variables declaration//GEN-END:variables
}
